<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>C# on 记录</title>
    <link>https://ffzznjxk.github.io/categories/c#/</link>
    <description>Recent content in C# on 记录</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>zh-CN</language>
    <lastBuildDate>Mon, 08 Feb 2021 00:00:00 +0000</lastBuildDate><atom:link href="https://ffzznjxk.github.io/categories/c#/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>选择集合与几何变换</title>
      <link>https://ffzznjxk.github.io/p/new-project-3/</link>
      <pubDate>Mon, 08 Feb 2021 00:00:00 +0000</pubDate>
      
      <guid>https://ffzznjxk.github.io/p/new-project-3/</guid>
      <description>选择集 选择集   获取选择
Editor.GetSelection()
  选择的内容
  SelectionSet = PromptSelectionResult.Value ObjectId[] = SelectionSet.GetObjectIds()
  类型DxfName
ObjectId.ObjectClass.DxfName
  /// &amp;lt;summary&amp;gt;  /// 按DxfName分类对象  /// &amp;lt;/summary&amp;gt; [CommandMethod(&amp;#34;SED&amp;#34;, CommandFlags.UsePickSet)] public void SelectEntityDxf() { Editor ed = AcadApp.DocumentManager.MdiActiveDocument.Editor; ////命令之前选中  //var psrAleady = ed.SelectImplied();  //选择集  var pso = new PromptSelectionOptions(); pso.MessageForAdding = &amp;#34;选择对象\n&amp;#34;; var psr = ed.GetSelection(pso); ////全部选中  //var psrA = ed.SelectAll();  //选择集  //PromptSelectionResult psrPolygon, psrCw, psrW;  ////选择多线段  //var per = ed.</description>
    </item>
    
    <item>
      <title>用户交互与几何图形</title>
      <link>https://ffzznjxk.github.io/p/new-project-2/</link>
      <pubDate>Mon, 01 Feb 2021 00:00:00 +0000</pubDate>
      
      <guid>https://ffzznjxk.github.io/p/new-project-2/</guid>
      <description>输入输出 输入  获取点提示 PromptPointOptions() 获取点结果 ed.GetPoint() 状态 PromptStatus.OK  输出  输出信息 ed.WriteMessage()  /// &amp;lt;summary&amp;gt;  /// 提示选择点  /// &amp;lt;/summary&amp;gt; [CommandMethod(&amp;#34;PromptSelectPoint&amp;#34;)] public void PromptSelectPoint() { //当前文档  Document doc = AcadApp.DocumentManager.MdiActiveDocument; //获得编辑器  Editor ed = doc.Editor; //获取点提示  var ppo = new PromptPointOptions(&amp;#34;\n指定起点&amp;#34;); //获取点结果  var ppr = ed.GetPoint(ppo); //结果状态为OK  if (ppr.Status == PromptStatus.OK) { //起点  Point3d startPt = ppr.Value; ppo = new PromptPointOptions(&amp;#34;\n指定终点&amp;#34;); ppr = ed.</description>
    </item>
    
    <item>
      <title>一个新项目</title>
      <link>https://ffzznjxk.github.io/p/new-project/</link>
      <pubDate>Sat, 09 Jan 2021 00:00:00 +0000</pubDate>
      
      <guid>https://ffzznjxk.github.io/p/new-project/</guid>
      <description>一个新项目 Visual Studio 1. 安装  登陆 语言  2. 创建新项目  解决方案 项目 项  3. HelloWorld  using namespace class  4. 工具  代码片段  5. 调试  断点 条件 监视（自动窗口/局部变量）  AutoCAD 1. 注册 2. 命令  line/point/vector/circle copy/move/scale/mirror block/dim/text  ObjectARX 1. 类库(.Net Framework)  4.5.2 AcDbMgd AcMgd  2. HelloWord  Editor Application  3. 调试  设为启动项 启动外部程序 NetLoad  4. Line  F12   /// &amp;lt;summary&amp;gt;  /// 新建直线(newline)  /// &amp;lt;/summary&amp;gt; [CommandMethod(&amp;#34;newline&amp;#34;)] public void NewLine() { //定义直线，起点：100, 100, 0；终点：300, 200, 0  Line line = new Line(new Point3d(100, 100, 0), new Point3d(300, 200, 0)); //打开当前图形数据库  Database db = HostApplicationServices.</description>
    </item>
    
  </channel>
</rss>
